jaffle_shop:
  target: postgres
  outputs:
    postgres:
      type: postgres
      host: localhost
      user: postgres
      password: Piomp234
      port: 5432
      dbname: postgres
      schema: dbt_models
      threads: 4